# Site settings
title: plwonks
email: abonnair@indiana.edu
description: > # this means to ignore newlines until "baseurl:"
  A collection of programming language enthusiasts from Indiana University.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wonks.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
future : true # so that pages in the future get built; doesn't work :/
highlighter: rouge
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

paginate: 10
