# Site settings
title: plwonks
email: cswords@umail.iu.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of programming language enthusiasts from Indiana University.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wonks.github.io" # the base hostname & protocol for your site
#twitter_username: cameronswords
#github_username:  cgswords

# Build settings
markdown: redcarpet
highlighter: pygments
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

paginate: 10
